version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto8
      nodejs: 12
    commands:
      - pwd
      - docker run -d -p 8000:8000 amazon/dynamodb-local 
      - sleep 5
  pre_build:
    commands:
      - echo Pre Build started on `date`
      - cd backend/ticket
      - npm ci
      - npm run build
  build:
    commands:
      - echo Build started on `date`
      - npm run test
  post_build:
    commands:
      - echo Build finished on `date`
reports:
  jest_reports:
    files:
      - jest.yml
    file-format: JUNITXML
    base-directory: reports
